# .github/workflows/publish.yml

name: Publish

on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@veeklabs'
      - run: yarn install --frozen-lockfile


      - name: Test
        run: yarn test


      - run: yarn   
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get the version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      -
        name: Prepare image tags
        id: prep
        run: |
          BRANCH=${GITHUB_REF##*/}
          TIMESTAMP=$(date +%s)
          # REGISTRY=us-east1-docker.pkg.dev/veek-internal
          # Cluster de dev foi desabilitado, todas as imagens serão enviadas para o cluster de produção
          REGISTRY=us-east1-docker.pkg.dev/veek-production
          if [ "${BRANCH}" = "live" ]; then
            REGISTRY=us-east1-docker.pkg.dev/veek-production
          fi
          DOCKER_IMAGE=${REGISTRY}/services/express-gateway
          TAGS="${DOCKER_IMAGE}:${BRANCH},${DOCKER_IMAGE}:${BRANCH}-sha-${GITHUB_SHA::8}-${TIMESTAMP},${{ steps.version.outputs.VERSION }}"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      -
        name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: us-east1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: NPM Token
        run: | 
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ./.npmrc
          echo "@veeklabs:registry=https://npm.pkg.github.com/" >> ./.npmrc


      - name: Test NPM token
        run: cat ./.npmrc

      -
        name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          platforms: linux/amd64
          build-args: |
            EG_VERSION=${{ steps.version.outputs.VERSION }}