# .github/workflows/publish.yml

name: Publish

on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@veeklabs'
      - run: yarn install --frozen-lockfile

      - run: yarn build && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}